name: Health check

on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check deployment
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-h9ll.onrender.com/version|https://full-stack-open-pokedex-h9ll.onrender.com
